server:
   port: 8094

spring:
   application:
      name: stock-service
   profiles:
      active: dev
   data:
      mongodb:
         host: localhost
         port: 2017
         uri: mongodb://localhost:27017/hackathon

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8091/eureka/
   instance:
      preferIpAddress: true
      hostName: 192.168.1.10