server:
   port: 8092

spring:
   application:
      name: ventas-service
   data:
      mongodb:
         host: localhost
         port: 27017
         uri: mongodb://localhost:27017/hackathon

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8091/eureka/
   instance:
      preferIpAddress: true
      hostName: 192.168.1.10